### ISSUE TITLE
是否考虑使用cp2102或者ch340保证can与usb串口同时工作。

### ISSUE THREAD

**Issue by Jiu-xiao** [Q1anWan/GY-H1#1]

**Comment by Q1anWan** [comment]
出于成本控制因素，本项目需求定义时确定CAN与USB是在差异化场景下的解决方案，因此设计的两种模式是CAN+UART或者USB+UART，并以此作为出发点，明确使用兆易创新MCU。如果明确需要CAN与USB同时启用，建议上位机配置USB转TTL模块并使用UART接口通讯。
