### ISSUE TITLE
IMU加热电阻咨询

### ISSUE THREAD

**Issue by qff233** [Q1anWan/GY-H1#3]
请问佬为何将nmos放在加热电阻的上端，nmos应该放到加热电阻的下端才会工作在饱和区吧，不然Vgs-Vth > Vds就进入了可变电阻区了呀。这个是故意设计，还是把他错当为pmos了？如果把nmos放到靠近地的位置的话，功率应该会提升到0.8W以上呀。

**Comment by Q1anWan** [comment]
The layout of heating resistors is limited by the board shape of PCBA. Anyway, it doesn't need such high heating power to maintain the work temperature.
